# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server-type: [config, tracing, discovery, gateway]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
		server-id: github
		server-username: ${env.GITHUB_ACTOR}
		server-password: ${env.GITHUB_TOKEN}
    - name: Build with Maven
      run: mvn -B package --file ${{matrix.server-type}}-server/pom.xml
    - name: Maven Release and Publish
      run: mvn -B -e deploy --file ${{matrix.server-type}}-server/pom.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/InstaCode/instacode-microservices-template-archetypes
      env:
        GITHUB_TOKEN: ${{ github.token }}