# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server-type: [config, tracing, discovery, gateway]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file ${{matrix.server-type}}-server/pom.xml
    - name: Maven Release and Publish
      uses: mg-smartrent/github-actions-maven-release@v1.5
      with:
        release-branch-name: "main"
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@example.com"
        access-token: ${{ secrets.GITHUB_TOKEN }}
        maven-project-folder: "${{matrix.server-type}}-server/"
#      run: mvn -B -e deploy --file ${{matrix.server-type}}-server/pom.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/InstaCode/instacode-microservices-template-archetypes
